name: Lambda Function Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'
  pull_request:
    branches:
      - main

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt

      - name: Run Tests
        run: python -m unittest discover lambda/tests

      - name: Package Lambda Function
        if: github.ref == 'refs/heads/main'
        run: |
          cd lambda
          zip -r9 ../function.zip .

      - name: Deploy Lambda Function
        if: github.ref == 'refs/heads/main'
        run: |
          aws lambda update-function-code --function-name YourLambdaFunctionName --zip-file fileb://function.zip
